name: Automatic Code Testing

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      # Клонируем код студента
      - name: Checkout Student's code
        uses: actions/checkout@v3

      # Клонируем тесты учителя
      - name: Checkout Teacher's tests
        uses: actions/checkout@v3
        with:
          repository: Alex286756/AutoTestsProbe
          path: tests

      # Устанавливаем JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Скачиваем зависимости JUnit
      - name: Download JUnit dependencies
        run: |
          mkdir lib
          wget -P lib https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/platform/junit-platform-launcher/1.9.2/junit-platform-launcher-1.9.2.jar
          wget -P lib https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.36/slf4j-simple-1.7.36.jar

      # Компиляция кода студента
      - name: Compile Student's code
        run: |
          javac -cp "lib/*:src" src/main/java/org/example/*.java

      # Компиляция тестов
      - name: Compile Tests
        run: |
          javac -cp "lib/*:tests:src" tests/java/org/example/*.java

      # Запуск тестов
      - name: Run Tests
        id: test-results
        run: |
          TEST_RESULT=$(mktemp)
          java -cp "lib/*:tests:src" org.junit.platform.console.ConsoleLauncher --scan-class-path > $TEST_RESULT
          echo "::set-output name=result::$(cat $TEST_RESULT)"
      
