name: Automatic Code Testing

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      # Клонируем код студента
      - name: Checkout Student's code
        uses: actions/checkout@v3

      # Клонируем тесты учителя
#      - name: Checkout Teacher's tests
#        uses: actions/checkout@v3
#        with:
#          repository: Alex286756/AutoTestsProbe
#          path: src/test

      # Устанавливаем JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Скачиваем зависимости JUnit
      - name: Download JUnit dependencies
        run: |
          mkdir lib
          wget -P lib https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter/5.8.1/junit-jupiter-5.8.1.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.8.1/junit-jupiter-api-5.8.1.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.8.1/junit-jupiter-engine-5.8.1.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-params/5.8.1/junit-jupiter-params-5.8.1.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.8.1/junit-platform-commons-1.8.1.jar
          wget -P lib https://repo1.maven.org/maven2/org/junit/platform/junit-platform-engine/1.8.1/junit-platform-engine-1.8.1.jar

      # Компиляция кода студента
      - name: Compile Student's code
        run: |
          javac -cp "lib/*:src" src/main/java/org/example/*.java

      # Компиляция тестов
      - name: Compile Tests
        run: |
          javac -cp "lib/*:tests:src" src/test/java/org/example/*.java

      # Запуск тестов
      - name: Run Tests
        id: test-results
        run: |
          TEST_RESULT=$(mktemp)
          java -cp "lib/*:tests:src" org.junit.platform.console.ConsoleLauncher --scan-class-path > $TEST_RESULT
          echo "::set-output name=result::$(cat $TEST_RESULT)"
      
