name: Java Core Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Student's code
        uses: actions/checkout@v3

      - name: Checkout Teacher's tests
        uses: actions/checkout@v3
        with:
          repository: Alex286756/AutoTestsProbe
#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: src/test

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Download JUnit dependencies
        run: |
          wget https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar
          wget https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console/1.9.2/junit-platform-console-1.9.2.jar
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-launcher/1.9.2/junit-platform-launcher-1.9.2.jar
          wget https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.36/slf4j-simple-1.7.36.jar
          wget https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar
          wget https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.17.2/log4j-core-2.17.2.jar

      - name: Compile Student's code
        run: |
          javac src/main/java/org/example/*.java
          # Если есть подпапки, добавьте их через пробел
          # javac src/main/java/package1/*.java src/main/java/package2/*.java

      - name: Compile code
        run: |
          javac -cp "junit-jupiter-api-5.9.2.jar:junit-jupiter-engine-5.9.2.jar:junit-platform-console-1.9.2.jar:junit-platform-commons-1.9.2.jar:junit-platform-launcher-1.9.2.jar:slf4j-simple-1.7.36.jar:log4j-api-2.17.2.jar:log4j-core-2.17.2.jar:src" src/main/java/org/example/*.java

#      - name: Run tests
#        run: |
#          java -cp "junit-jupiter-api-5.9.2.jar:junit-jupiter-engine-5.9.2.jar:junit-platform-console-1.9.2.jar:junit-platform-commons-1.9.2.jar:junit-platform-launcher-1.9.2.jar:slf4j-simple-1.7.36.jar:log4j-api-2.17.2.jar:log4j-core-2.17.2.jar:src" \
#          org.junit.platform.console.ConsoleLauncher --scan-class-path

      - name: Compile Tests
        run: |
          javac src/test/java/org/example/*.java -cp .:src/test/java

      - name: Run Tests
        run: |
          java -cp .:src/test/java TestRunner
          # Замените TestRunner на имя вашего тестового класса
#
#      - name: Add comment on failure
#        if: failure()
#        uses: actions/github-script@v6
#        with:
#          script: |
#            github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: '⚠️ Тесты не прошли! Подробности: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
#            })
